Repository ResidenciaTICBrisa/T2G6-Jogo-Unity-BOSS, pull requests merged in 2024-04, with the labels that each got.

#28 fix: Corrigindo contato entre collider e personagem
  Unity-Project/Assets/Materials.meta
  Unity-Project/Assets/Materials/ColliderFriction.physicsMaterial2D
  Unity-Project/Assets/Materials/ColliderFriction.physicsMaterial2D.meta
  Unity-Project/Assets/Scenes/CityMap.unity
Labels: bug

#38 docs: Envio das ATAS #37
  docs/ATAS/ATA - 09_05.pdf
  docs/ATAS/ATA - 16_05.pdf
Labels: documentation

#43 feat#31: Robo Adicionado
  Unity-Project/Assets/Animations/Characters/RobotT1.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1 1.controller
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1 1.controller.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1.controller
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1.controller.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1.prefab
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1.prefab.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1back.anim
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1back.anim.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1back.png
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1back.png.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1front.anim
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1front.anim.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1front.png
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1front.png.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1left.anim
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1left.anim.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1left.png
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1left.png.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1right.anim
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1right.anim.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1right.png
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1right.png.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1stopped.anim
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1stopped.anim.meta
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1stopped.png
  Unity-Project/Assets/Animations/Characters/RobotT1/RobotT1stopped.png.meta
  Unity-Project/Assets/Scenes/RobotT1.unity
  Unity-Project/Assets/Scenes/RobotT1.unity.meta
  Unity-Project/Assets/Scripts/StoreScripts.cs
  Unity-Project/Assets/Scripts/StoreScripts.cs.meta
  Unity-Project/Assets/Sprites/Characters/RobotT1.meta
  Unity-Project/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement
